class DataConfig:
    """主要的作用用于取表格某字段的数据"""

    case_id = "用例ID"
    case_model_1 = "一级模块"
    case_name_2 = "二级模块"
    title = "标题"
    priority = "优先级"
    url = "请求URL"
    pre_exec = "前置条件"
    expected_result = "预期结果"
    actual_result = "实际结果"
    assert_fail_hint = "报错的提示信息"
    location_fail_hint = "定时失败提示"
    data = "操作的数据结构"
